# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AgregaPaciente_Ventana.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AgregaPac_ventana(object):
    def setupUi(self, AgregaPac_ventana):
        AgregaPac_ventana.setObjectName("AgregaPac_ventana")
        AgregaPac_ventana.resize(571, 461)
        self.label = QtWidgets.QLabel(AgregaPac_ventana)
        self.label.setGeometry(QtCore.QRect(40, 20, 41, 16))
        self.label.setObjectName("label")
        self.cajaNombre = QtWidgets.QTextEdit(AgregaPac_ventana)
        self.cajaNombre.setGeometry(QtCore.QRect(100, 20, 256, 21))
        self.cajaNombre.setObjectName("cajaNombre")
        self.Aceptar_bot_agrPac = QtWidgets.QPushButton(AgregaPac_ventana)
        self.Aceptar_bot_agrPac.setGeometry(QtCore.QRect(360, 420, 75, 23))
        self.Aceptar_bot_agrPac.setObjectName("Aceptar_bot_agrPac")
        self.Cancelar_bot_AgrPac = QtWidgets.QPushButton(AgregaPac_ventana)
        self.Cancelar_bot_AgrPac.setGeometry(QtCore.QRect(450, 420, 75, 23))
        self.Cancelar_bot_AgrPac.setObjectName("Cancelar_bot_AgrPac")
        self.label_4 = QtWidgets.QLabel(AgregaPac_ventana)
        self.label_4.setGeometry(QtCore.QRect(260, 380, 61, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(AgregaPac_ventana)
        self.label_5.setGeometry(QtCore.QRect(30, 380, 61, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(AgregaPac_ventana)
        self.label_6.setGeometry(QtCore.QRect(30, 180, 61, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(AgregaPac_ventana)
        self.label_7.setGeometry(QtCore.QRect(30, 90, 61, 16))
        self.label_7.setObjectName("label_7")
        self.radioButton_estable = QtWidgets.QRadioButton(AgregaPac_ventana)
        self.radioButton_estable.setGeometry(QtCore.QRect(340, 380, 61, 17))
        self.radioButton_estable.setObjectName("radioButton_estable")
        self.label_2 = QtWidgets.QLabel(AgregaPac_ventana)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 54, 20))
        self.label_2.setObjectName("label_2")
        self.cajaDiagnostico = QtWidgets.QTextEdit(AgregaPac_ventana)
        self.cajaDiagnostico.setGeometry(QtCore.QRect(20, 110, 531, 61))
        self.cajaDiagnostico.setObjectName("cajaDiagnostico")
        self.cajaAlergias = QtWidgets.QTextEdit(AgregaPac_ventana)
        self.cajaAlergias.setGeometry(QtCore.QRect(20, 200, 531, 61))
        self.cajaAlergias.setObjectName("cajaAlergias")
        self.radioButton_grave = QtWidgets.QRadioButton(AgregaPac_ventana)
        self.radioButton_grave.setGeometry(QtCore.QRect(410, 380, 61, 17))
        self.radioButton_grave.setObjectName("radioButton_grave")
        self.label_3 = QtWidgets.QLabel(AgregaPac_ventana)
        self.label_3.setGeometry(QtCore.QRect(30, 270, 141, 16))
        self.label_3.setObjectName("label_3")
        self.cajaComentario = QtWidgets.QTextEdit(AgregaPac_ventana)
        self.cajaComentario.setGeometry(QtCore.QRect(20, 300, 531, 61))
        self.cajaComentario.setObjectName("cajaComentario")
        self.comboBox_Habitacion = QtWidgets.QComboBox(AgregaPac_ventana)
        self.comboBox_Habitacion.setGeometry(QtCore.QRect(100, 50, 43, 20))
        self.comboBox_Habitacion.setObjectName("comboBox_Habitacion")
        self.comboBox_Habitacion.addItem("")
        self.comboBox_Habitacion.addItem("")
        self.comboBox_Habitacion.addItem("")
        self.comboBox_Habitacion.addItem("")
        self.comboBox_Habitacion.addItem("")
        self.comboBox_preAlta = QtWidgets.QComboBox(AgregaPac_ventana)
        self.comboBox_preAlta.setGeometry(QtCore.QRect(80, 380, 69, 22))
        self.comboBox_preAlta.setObjectName("comboBox_preAlta")
        self.comboBox_preAlta.addItem("")
        self.comboBox_preAlta.addItem("")
        self.radioButton_critico = QtWidgets.QRadioButton(AgregaPac_ventana)
        self.radioButton_critico.setGeometry(QtCore.QRect(480, 380, 71, 17))
        self.radioButton_critico.setObjectName("radioButton_critico")

        self.retranslateUi(AgregaPac_ventana)
        QtCore.QMetaObject.connectSlotsByName(AgregaPac_ventana)

    def retranslateUi(self, AgregaPac_ventana):
        _translate = QtCore.QCoreApplication.translate
        AgregaPac_ventana.setWindowTitle(_translate("AgregaPac_ventana", "Agregar un nuevo paciente"))
        self.label.setText(_translate("AgregaPac_ventana", "Nombre:"))
        self.Aceptar_bot_agrPac.setText(_translate("AgregaPac_ventana", "Aceptar"))
        self.Cancelar_bot_AgrPac.setText(_translate("AgregaPac_ventana", "Cancelar"))
        self.label_4.setText(_translate("AgregaPac_ventana", "Gravedad:"))
        self.label_5.setText(_translate("AgregaPac_ventana", "Pre-alta:"))
        self.label_6.setText(_translate("AgregaPac_ventana", "Alergias"))
        self.label_7.setText(_translate("AgregaPac_ventana", "Diagnóstico"))
        self.radioButton_estable.setText(_translate("AgregaPac_ventana", "Estable"))
        self.label_2.setText(_translate("AgregaPac_ventana", "Habitación:"))
        self.radioButton_grave.setText(_translate("AgregaPac_ventana", "Grave"))
        self.label_3.setText(_translate("AgregaPac_ventana", "Comentarios adicionales"))
        self.comboBox_Habitacion.setItemText(0, _translate("AgregaPac_ventana", "501"))
        self.comboBox_Habitacion.setItemText(1, _translate("AgregaPac_ventana", "502"))
        self.comboBox_Habitacion.setItemText(2, _translate("AgregaPac_ventana", "503"))
        self.comboBox_Habitacion.setItemText(3, _translate("AgregaPac_ventana", "504"))
        self.comboBox_Habitacion.setItemText(4, _translate("AgregaPac_ventana", "505"))
        self.comboBox_preAlta.setItemText(0, _translate("AgregaPac_ventana", "No"))
        self.comboBox_preAlta.setItemText(1, _translate("AgregaPac_ventana", "Sí"))
        self.radioButton_critico.setText(_translate("AgregaPac_ventana", "Crítico"))
