# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Pacientes_Ventana.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PacientesVentana(object):
    def setupUi(self, PacientesVentana):
        PacientesVentana.setObjectName("PacientesVentana")
        PacientesVentana.resize(847, 607)
        self.tabWidget = QtWidgets.QTabWidget(PacientesVentana)
        self.tabWidget.setGeometry(QtCore.QRect(10, 60, 821, 531))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.boton_bloquearControl = QtWidgets.QPushButton(self.tab)
        self.boton_bloquearControl.setGeometry(QtCore.QRect(620, 270, 181, 51))
        self.boton_bloquearControl.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ImagPlus/blocked.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.boton_bloquearControl.setIcon(icon)
        self.boton_bloquearControl.setIconSize(QtCore.QSize(40, 40))
        self.boton_bloquearControl.setObjectName("boton_bloquearControl")
        self.boton_regresarCentral = QtWidgets.QPushButton(self.tab)
        self.boton_regresarCentral.setGeometry(QtCore.QRect(420, 270, 191, 51))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ImagPlus/centralEnf.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.boton_regresarCentral.setIcon(icon1)
        self.boton_regresarCentral.setIconSize(QtCore.QSize(40, 40))
        self.boton_regresarCentral.setObjectName("boton_regresarCentral")
        self.boton_enviarRobot = QtWidgets.QPushButton(self.tab)
        self.boton_enviarRobot.setGeometry(QtCore.QRect(240, 330, 121, 41))
        self.boton_enviarRobot.setObjectName("boton_enviarRobot")
        self.caja_localizacionActual = QtWidgets.QTextEdit(self.tab)
        self.caja_localizacionActual.setGeometry(QtCore.QRect(140, 80, 141, 21))
        self.caja_localizacionActual.setObjectName("caja_localizacionActual")
        self.comboBox_habitMP = QtWidgets.QComboBox(self.tab)
        self.comboBox_habitMP.setGeometry(QtCore.QRect(90, 160, 69, 22))
        self.comboBox_habitMP.setObjectName("comboBox_habitMP")
        self.comboBox_habitMP.addItem("")
        self.comboBox_habitMP.addItem("")
        self.comboBox_habitMP.addItem("")
        self.comboBox_habitMP.addItem("")
        self.comboBox_habitMP.addItem("")
        self.label_23 = QtWidgets.QLabel(self.tab)
        self.label_23.setGeometry(QtCore.QRect(30, 160, 61, 16))
        self.label_23.setObjectName("label_23")
        self.caja_mensajePaciente = QtWidgets.QTextEdit(self.tab)
        self.caja_mensajePaciente.setGeometry(QtCore.QRect(20, 220, 341, 101))
        self.caja_mensajePaciente.setObjectName("caja_mensajePaciente")
        self.label_24 = QtWidgets.QLabel(self.tab)
        self.label_24.setGeometry(QtCore.QRect(20, 190, 151, 16))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.tab)
        self.label_25.setGeometry(QtCore.QRect(20, 80, 101, 16))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.tab)
        self.label_26.setGeometry(QtCore.QRect(20, 130, 141, 16))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.tab)
        self.label_27.setGeometry(QtCore.QRect(40, 30, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(16)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.boton_adelante = QtWidgets.QPushButton(self.tab)
        self.boton_adelante.setGeometry(QtCore.QRect(550, 330, 121, 51))
        self.boton_adelante.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/ImagPlus/expand.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.boton_adelante.setIcon(icon2)
        self.boton_adelante.setIconSize(QtCore.QSize(40, 40))
        self.boton_adelante.setObjectName("boton_adelante")
        self.boton_alto = QtWidgets.QPushButton(self.tab)
        self.boton_alto.setGeometry(QtCore.QRect(550, 390, 121, 51))
        self.boton_alto.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/ImagPlus/stop-button.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.boton_alto.setIcon(icon3)
        self.boton_alto.setIconSize(QtCore.QSize(40, 40))
        self.boton_alto.setObjectName("boton_alto")
        self.boton_izquierda = QtWidgets.QPushButton(self.tab)
        self.boton_izquierda.setGeometry(QtCore.QRect(420, 390, 121, 51))
        self.boton_izquierda.setStyleSheet("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/ImagPlus/arrow.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.boton_izquierda.setIcon(icon4)
        self.boton_izquierda.setIconSize(QtCore.QSize(40, 40))
        self.boton_izquierda.setObjectName("boton_izquierda")
        self.boton_derecha = QtWidgets.QPushButton(self.tab)
        self.boton_derecha.setGeometry(QtCore.QRect(680, 390, 121, 51))
        self.boton_derecha.setStyleSheet("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/ImagPlus/right-chevron.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.boton_derecha.setIcon(icon5)
        self.boton_derecha.setIconSize(QtCore.QSize(40, 40))
        self.boton_derecha.setObjectName("boton_derecha")
        self.boton_atras = QtWidgets.QPushButton(self.tab)
        self.boton_atras.setGeometry(QtCore.QRect(550, 450, 121, 51))
        self.boton_atras.setStyleSheet("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/ImagPlus/down.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.boton_atras.setIcon(icon6)
        self.boton_atras.setIconSize(QtCore.QSize(40, 40))
        self.boton_atras.setObjectName("boton_atras")
        self.label_28 = QtWidgets.QLabel(self.tab)
        self.label_28.setGeometry(QtCore.QRect(180, 140, 41, 41))
        self.label_28.setStyleSheet("image: url(:/ImagPlus/pin.png);")
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.caja_streaming = QtWidgets.QLabel(self.tab)
        self.caja_streaming.setGeometry(QtCore.QRect(420, 10, 381, 251))
        self.caja_streaming.setFrameShape(QtWidgets.QFrame.Box)
        self.caja_streaming.setFrameShadow(QtWidgets.QFrame.Raised)
        self.caja_streaming.setLineWidth(3)
        self.caja_streaming.setMidLineWidth(0)
        self.caja_streaming.setText("")
        self.caja_streaming.setObjectName("caja_streaming")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.AgregPac_Boton = QtWidgets.QPushButton(self.tab_2)
        self.AgregPac_Boton.setGeometry(QtCore.QRect(130, 20, 191, 51))
        self.AgregPac_Boton.setToolTip("")
        self.AgregPac_Boton.setWhatsThis("")
        self.AgregPac_Boton.setStyleSheet("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Imag/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.AgregPac_Boton.setIcon(icon7)
        self.AgregPac_Boton.setIconSize(QtCore.QSize(30, 30))
        self.AgregPac_Boton.setObjectName("AgregPac_Boton")
        self.tablaPacientes = QtWidgets.QTableWidget(self.tab_2)
        self.tablaPacientes.setGeometry(QtCore.QRect(10, 90, 311, 401))
        self.tablaPacientes.setObjectName("tablaPacientes")
        self.tablaPacientes.setColumnCount(4)
        self.tablaPacientes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablaPacientes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaPacientes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaPacientes.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaPacientes.setHorizontalHeaderItem(3, item)
        self.scrollArea = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea.setGeometry(QtCore.QRect(350, 0, 461, 501))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 100))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -271, 442, 770))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.grafica_temperatura = PlotWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grafica_temperatura.sizePolicy().hasHeightForWidth())
        self.grafica_temperatura.setSizePolicy(sizePolicy)
        self.grafica_temperatura.setMinimumSize(QtCore.QSize(100, 150))
        self.grafica_temperatura.setObjectName("grafica_temperatura")
        self.gridLayout.addWidget(self.grafica_temperatura, 12, 0, 1, 5)
        self.grafica_oximetria = PlotWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grafica_oximetria.sizePolicy().hasHeightForWidth())
        self.grafica_oximetria.setSizePolicy(sizePolicy)
        self.grafica_oximetria.setMinimumSize(QtCore.QSize(100, 150))
        self.grafica_oximetria.setObjectName("grafica_oximetria")
        self.gridLayout.addWidget(self.grafica_oximetria, 15, 0, 1, 5)
        self.etiqueta_gravedad = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.etiqueta_gravedad.setMinimumSize(QtCore.QSize(0, 0))
        self.etiqueta_gravedad.setText("")
        self.etiqueta_gravedad.setObjectName("etiqueta_gravedad")
        self.gridLayout.addWidget(self.etiqueta_gravedad, 9, 1, 1, 1)
        self.EditarPac_boton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.EditarPac_boton.setToolTip("")
        self.EditarPac_boton.setWhatsThis("")
        self.EditarPac_boton.setStyleSheet("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/ImagPlus/pencil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.EditarPac_boton.setIcon(icon8)
        self.EditarPac_boton.setIconSize(QtCore.QSize(30, 30))
        self.EditarPac_boton.setObjectName("EditarPac_boton")
        self.gridLayout.addWidget(self.EditarPac_boton, 16, 0, 1, 1)
        self.etiqueta_alergias = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.etiqueta_alergias.setObjectName("etiqueta_alergias")
        self.gridLayout.addWidget(self.etiqueta_alergias, 6, 0, 1, 5)
        self.etiqueta_comentarios = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.etiqueta_comentarios.setObjectName("etiqueta_comentarios")
        self.gridLayout.addWidget(self.etiqueta_comentarios, 8, 0, 1, 5)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.etiqueta_diagnostico = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.etiqueta_diagnostico.setObjectName("etiqueta_diagnostico")
        self.gridLayout.addWidget(self.etiqueta_diagnostico, 4, 0, 1, 5)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 9, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 7, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.etiqueta_nombre = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.etiqueta_nombre.setText("")
        self.etiqueta_nombre.setObjectName("etiqueta_nombre")
        self.gridLayout.addWidget(self.etiqueta_nombre, 1, 0, 1, 3)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 11, 0, 1, 2)
        self.etiqueta_preAlta = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.etiqueta_preAlta.setText("")
        self.etiqueta_preAlta.setObjectName("etiqueta_preAlta")
        self.gridLayout.addWidget(self.etiqueta_preAlta, 9, 4, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 14, 0, 1, 1)
        self.etiqueta_habitacion = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.etiqueta_habitacion.setText("")
        self.etiqueta_habitacion.setObjectName("etiqueta_habitacion")
        self.gridLayout.addWidget(self.etiqueta_habitacion, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 9, 3, 1, 1)
        self.EliminaPac_boton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.EliminaPac_boton.setToolTip("")
        self.EliminaPac_boton.setWhatsThis("")
        self.EliminaPac_boton.setStyleSheet("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("Imag/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.EliminaPac_boton.setIcon(icon9)
        self.EliminaPac_boton.setIconSize(QtCore.QSize(30, 30))
        self.EliminaPac_boton.setObjectName("EliminaPac_boton")
        self.gridLayout.addWidget(self.EliminaPac_boton, 16, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setGeometry(QtCore.QRect(20, 10, 81, 71))
        self.label_21.setStyleSheet("image: url(:/ImagPlus/patient.png);")
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tablaEstadisticas = QtWidgets.QTableWidget(self.tab_3)
        self.tablaEstadisticas.setGeometry(QtCore.QRect(20, 80, 311, 351))
        self.tablaEstadisticas.setObjectName("tablaEstadisticas")
        self.tablaEstadisticas.setColumnCount(3)
        self.tablaEstadisticas.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablaEstadisticas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaEstadisticas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaEstadisticas.setHorizontalHeaderItem(2, item)
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(390, 20, 51, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(390, 60, 61, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(390, 90, 51, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(390, 120, 51, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        self.label_15.setGeometry(QtCore.QRect(620, 60, 121, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tab_3)
        self.label_16.setGeometry(QtCore.QRect(390, 150, 131, 16))
        self.label_16.setObjectName("label_16")
        self.eti_hab_est = QtWidgets.QLabel(self.tab_3)
        self.eti_hab_est.setGeometry(QtCore.QRect(460, 60, 47, 13))
        self.eti_hab_est.setText("")
        self.eti_hab_est.setObjectName("eti_hab_est")
        self.eti_dia_est = QtWidgets.QLabel(self.tab_3)
        self.eti_dia_est.setGeometry(QtCore.QRect(430, 90, 47, 13))
        self.eti_dia_est.setText("")
        self.eti_dia_est.setObjectName("eti_dia_est")
        self.eti_hora_est = QtWidgets.QLabel(self.tab_3)
        self.eti_hora_est.setGeometry(QtCore.QRect(430, 120, 47, 13))
        self.eti_hora_est.setText("")
        self.eti_hora_est.setObjectName("eti_hora_est")
        self.eti_duracion_est = QtWidgets.QLabel(self.tab_3)
        self.eti_duracion_est.setGeometry(QtCore.QRect(740, 60, 47, 13))
        self.eti_duracion_est.setText("")
        self.eti_duracion_est.setObjectName("eti_duracion_est")
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setGeometry(QtCore.QRect(400, 180, 61, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab_3)
        self.label_18.setGeometry(QtCore.QRect(400, 200, 81, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.tab_3)
        self.label_19.setGeometry(QtCore.QRect(400, 220, 41, 16))
        self.label_19.setObjectName("label_19")
        self.label_22 = QtWidgets.QLabel(self.tab_3)
        self.label_22.setGeometry(QtCore.QRect(130, 10, 81, 61))
        self.label_22.setStyleSheet("image: url(:/ImagPlus/statistics.png);")
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.tabWidget.addTab(self.tab_3, "")
        self.label = QtWidgets.QLabel(PacientesVentana)
        self.label.setGeometry(QtCore.QRect(20, 10, 321, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Kozuka Gothic Pr6N M")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_20 = QtWidgets.QLabel(PacientesVentana)
        self.label_20.setGeometry(QtCore.QRect(280, 10, 71, 61))
        self.label_20.setStyleSheet("image: url(:/ImagPlus/hospital.png);")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")

        self.retranslateUi(PacientesVentana)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PacientesVentana)

    def retranslateUi(self, PacientesVentana):
        _translate = QtCore.QCoreApplication.translate
        PacientesVentana.setWindowTitle(_translate("PacientesVentana", "Robid"))
        self.boton_bloquearControl.setText(_translate("PacientesVentana", "Bloquear control"))
        self.boton_regresarCentral.setText(_translate("PacientesVentana", "Regresar a la central"))
        self.boton_enviarRobot.setText(_translate("PacientesVentana", "Enviar al robot"))
        self.comboBox_habitMP.setItemText(0, _translate("PacientesVentana", "501"))
        self.comboBox_habitMP.setItemText(1, _translate("PacientesVentana", "502"))
        self.comboBox_habitMP.setItemText(2, _translate("PacientesVentana", "503"))
        self.comboBox_habitMP.setItemText(3, _translate("PacientesVentana", "504"))
        self.comboBox_habitMP.setItemText(4, _translate("PacientesVentana", "505"))
        self.label_23.setText(_translate("PacientesVentana", "Habitación:"))
        self.label_24.setText(_translate("PacientesVentana", "Mensaje para el paciente:"))
        self.label_25.setText(_translate("PacientesVentana", "Localización actual:"))
        self.label_26.setText(_translate("PacientesVentana", "Seleccionar nuevo destino:"))
        self.label_27.setText(_translate("PacientesVentana", "Robid"))
        self.boton_adelante.setText(_translate("PacientesVentana", "Adelante"))
        self.boton_alto.setText(_translate("PacientesVentana", "Alto"))
        self.boton_izquierda.setText(_translate("PacientesVentana", "Izquierda"))
        self.boton_derecha.setText(_translate("PacientesVentana", "Derecha"))
        self.boton_atras.setText(_translate("PacientesVentana", "Atrás"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("PacientesVentana", "Menú principal"))
        self.AgregPac_Boton.setText(_translate("PacientesVentana", "Agregar paciente"))
        item = self.tablaPacientes.horizontalHeaderItem(0)
        item.setText(_translate("PacientesVentana", "Nombre"))
        item = self.tablaPacientes.horizontalHeaderItem(1)
        item.setText(_translate("PacientesVentana", "Habitación"))
        item = self.tablaPacientes.horizontalHeaderItem(2)
        item.setText(_translate("PacientesVentana", "Gravedad"))
        item = self.tablaPacientes.horizontalHeaderItem(3)
        item.setText(_translate("PacientesVentana", "Pre-alta"))
        self.EditarPac_boton.setText(_translate("PacientesVentana", "Editar paciente"))
        self.label_3.setText(_translate("PacientesVentana", "Habitación:"))
        self.label_7.setText(_translate("PacientesVentana", "Diagnóstico:"))
        self.label_6.setText(_translate("PacientesVentana", "Alergias:"))
        self.label_4.setText(_translate("PacientesVentana", "Gravedad:"))
        self.label_8.setText(_translate("PacientesVentana", "Comentarios adicionales:"))
        self.label_2.setText(_translate("PacientesVentana", "Nombre:"))
        self.label_9.setText(_translate("PacientesVentana", "Datos de temperatura:"))
        self.label_10.setText(_translate("PacientesVentana", "Datos de oximetría:"))
        self.label_5.setText(_translate("PacientesVentana", "Pre-alta:"))
        self.EliminaPac_boton.setText(_translate("PacientesVentana", "Eliminar paciente"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("PacientesVentana", "Pacientes"))
        item = self.tablaEstadisticas.horizontalHeaderItem(0)
        item.setText(_translate("PacientesVentana", "Habitación"))
        item = self.tablaEstadisticas.horizontalHeaderItem(1)
        item.setText(_translate("PacientesVentana", "Día"))
        item = self.tablaEstadisticas.horizontalHeaderItem(2)
        item.setText(_translate("PacientesVentana", "Hora"))
        self.label_11.setText(_translate("PacientesVentana", "Recorrido"))
        self.label_12.setText(_translate("PacientesVentana", "Habitación:"))
        self.label_13.setText(_translate("PacientesVentana", "Día:"))
        self.label_14.setText(_translate("PacientesVentana", "Hora:"))
        self.label_15.setText(_translate("PacientesVentana", "Duración del recorrido:"))
        self.label_16.setText(_translate("PacientesVentana", "Se tomaron muestras de:"))
        self.label_17.setText(_translate("PacientesVentana", "-Oximetría:"))
        self.label_18.setText(_translate("PacientesVentana", "-Temperatura:"))
        self.label_19.setText(_translate("PacientesVentana", "-Pulso:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("PacientesVentana", "Estadísticas"))
        self.label.setText(_translate("PacientesVentana", "Hospital | Piso 5"))
from pyqtgraph import PlotWidget
import Imag_rc
